version: "3.8"

services:
  app: 
    # container_name:
    build:
      context: .
      dockerfile: ./docker/app/app.dockerfile
    volumes:
      - ./src/:/var/www/html
  
  web:
    # container_name:
    build:
      context: .
      dockerfile: ./docker/web/web.dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
  
  db:
    # container_name:
    build:
      context: .
      dockerfile: ./docker/db/db.dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    # container_name:
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
      
volumes:
  mysql-volume: